// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sygznlcuxdebbrlzsnrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Z3pubGN1eGRlYmJybHpzbnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDUzNDksImV4cCI6MjA3MTAyMTM0OX0.AyYbUxzglaaQRSsOFEo51-idgtlA9c1T7TgKb53Ws1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});